apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tony-certificate
  namespace: sock-shop
spec:
  secretName: tony-secret
  issuerRef: 
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: tonynoah.me
  dnsNames:
  - tonynoah.me
 