name: Deploy to AKS
#hello world
'on':
  push:
    branches:
      - main
    paths:
      - terraform/**
      - my-app/**

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0
      - name: Terraform Init
        run: terraform init
      - name: Terraform Plan
        run: terraform plan
      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          ARM_CLIENT_ID: '${{ secrets.AZURE_CLIENT_ID }}'
          ARM_CLIENT_SECRET: '${{ secrets.AZURE_CLIENT_SECRET }}'
          ARM_SUBSCRIPTION_ID: '${{ secrets.AZURE_SUBSCRIPTION_ID }}'
          ARM_TENANT_ID: '${{ secrets.AZURE_TENANT_ID }}'
  deploy:
    runs-on: ubuntu-latest
    needs: terraform
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 1.26.0
      - name: Configure kubectl
        run: >
          az aks get-credentials --resource-group samuel-rg --name
          munachimso
        env:
          AZURE_CREDENTIALS: '${{ secrets.AZURE_CREDENTIALS }}'
      - name: Apply Kubernetes Manifests
        run: |
          kubectl apply -f my-app/templates/
      - name: Verify Deployment
        run: |
          kubectl rollout status tony-capstone-project/my-app
      - name: Apply Prometheus and Grafana
        run: >
          helm repo add prometheus-community
          https://prometheus-community.github.io/helm-charts

          helm install prome prometheus-community/kube-prometheus-stack -n
          sock-shop
